# Change these first
owner: Novatra # Your GitHub organization or username, where this repository lives
repo: uptimer # The name of this repository

sites:
  - name: Novatra
    url: https://novatra.in

assignees: # Users to assign downtime issues (optional)
  - SpreadSheets600
  - Utkarsh-username
  - udit-001

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  theme: light
  themeUrl: https://status.novatra.in/novatra-theme.css
  cname: status.novatra.in
  logoUrl: https://raw.githubusercontent.com/Novatra/assets/refs/heads/main/logos/novatra.png
  favicon: https://novatra.in/static/imgs/favicon.ico
  name: Novatra Status Page
  navbar:
    - title: Visit Site
      href: https://novatra.in
workflowSchedule:
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
